### ISSUE TITLE
Use custom database

### ISSUE THREAD

**Issue by nikolicjakov** [crinis/sourcebans-docker#2]
Is it possible that you integrate database variables in sourcebans image.

For example i have mysql server running serving multiple databases. So i dont want to start dedicated mysql server instance to server only sourcebans. If there could be way to configure database HOST, USER and PASSWORD trough container parameters it would be great.

**Comment by crinis** [comment]
It is no problem to use a custom database.  Just start the SourceBans container without the database container. During your first start SourceBans should allow you to configure any database in the frontend at example.com/install .

**Comment by nikolicjakov** [comment]
If that is the case i will close this issue.
