### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by Tolfx** [crinis/sourcebans-docker#3]
I made a docker-compose.yml and etc so nothing on the docker side is the fault.. but as I ssh into the docker I saw there were some missing files? Since when going to the page I can't seem to find /install, so I installed sourcebans web and checked what was missing and..

The following missing `items` will be included here:
`/install`
`/updater`
`index.php`

I don't know if this is meant to be like this, but I think there has been an mistake somewhere while installing since there is no /install in var/www/html.

![image](https://user-images.githubusercontent.com/57797792/99115627-053b8700-25f3-11eb-84c7-9a865dc84938.png)

Thanks for reading

**Comment by crinis** [comment]
Make sure to set the "REMOVE_SETUP_DIRS" environment variable to false. If you did it might be to the formerly used environment variable "INSTALL" that was still used in the entrypoint script. Have removed it.

Could you try the latest release? crinis/sourcebans:0.6.0

**Comment by Tolfx** [comment]
Ah my bad, sorry for the issues.
